task/urls.py
from django.urls import path

from task.views import (
    TaskListView,
    index,
    TaskDetailView,
    toggle_assign_to_task,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerDeleteView,
    WorkerUpdateView,
    WorkerCreateView,
    finish_task,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "tasks/",
        TaskListView.as_view(),
        name="task-list",
    ),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path(
        "tasks/<int:pk>/toggle-assign/",
        toggle_assign_to_task,
        name="toggle-task-assign",
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="tasks-create",
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete",
    ),
    path(
        "workers/",
        WorkerListView.as_view(),
        name="worker-list",
    ),
    path(
        "workers/create/",
        WorkerCreateView.as_view(),
        name="worker-create",
    ),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update",
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete",
    ),
    path(
        "tasks/<int:pk>/finish-task/",
        finish_task,
        name="finish-task",
    ),
    path(
        "tasktypes/",
        TaskTypeListView.as_view(),
        name="tasktype-list",
    ),
    path(
        "tasktypes/create/",
        TaskTypeCreateView.as_view(),
        name="tasktype-create",
    ),
    path(
        "tasktypes/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="tasktype-update",
    ),
    path(
        "tasktypes/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="tasktype-delete",
    ),
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list",
    ),
    path(
        "position/create/",
        PositionCreateView.as_view(),
        name="position-create",
    ),
    path(
        "position/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "position/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
]

app_name = "task"

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task.urls", namespace="task")),
    path("accounts/", include("django.contrib.auth.urls")),
]

task/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from task_manager.settings import AUTH_USER_MODEL


class Position(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"


class TaskType(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"


class Worker(AbstractUser):
    position = models.ForeignKey(Position, on_delete=models.CASCADE, default=1)

    class Meta:
        verbose_name = "worker"
        verbose_name_plural = "workers"
        ordering = ["username"]

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    # def get_absolute_url(self):
    #     return reverse("taxi:driver-detail", kwargs={"pk": self.pk})


class Task(models.Model):
    PRIORITY_CHOICES = (
        ("Low", "Low"),
        ("Medium", "Medium"),
        ("High", "High"),
    )
    name = models.CharField(max_length=255)
    status = models.CharField(max_length=255, default="In progress")
    description = models.TextField()
    deadline = models.DateField()
    is_completed = models.BooleanField()
    priority = models.CharField(
        max_length=10,
        choices=PRIORITY_CHOICES,
        default="LOW",
    )
    task_type = models.ForeignKey(TaskType, on_delete=models.CASCADE)
    assignees = models.ManyToManyField(AUTH_USER_MODEL, related_name="tasks")

    class Meta:
        ordering = ["deadline"]

    def __str__(self):
        return self.name

task/forms.py
from datetime import datetime

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from task.models import Task, Worker


class TaskForm(forms.ModelForm):
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Task
        fields = "__all__"

    def clean_deadline(self):
        if self.cleaned_data["deadline"] < datetime.now().date():
            raise ValidationError(
                "Deadline can not be earlier than today"
            )
        return self.cleaned_data["deadline"]


class WorkerCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "position",
            "first_name",
            "last_name",
        )


class WorkerSearchForm(forms.Form):
    username = forms.CharField(
        max_length=150,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by username"}
        )
    )


class TaskSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        )
    )


class TaskTypeSearchForm(forms.Form):

    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search"}),
    )


class PositionSearchForm(forms.Form):

    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search"}),
    )

task/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from task.forms import (
    TaskSearchForm,
    TaskForm,
    WorkerSearchForm,
    WorkerCreationForm,
    TaskTypeSearchForm,
    PositionSearchForm,
)
from task.models import Task, Worker, TaskType, Position


def index(request):
    """View function for the home page of the site."""

    num_workers = Worker.objects.count()
    num_tasks = Task.objects.count()
    num_positions = Position.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_workers": num_workers,
        "num_tasks": num_tasks,
        "num_positions": num_positions,
        "num_visits": num_visits + 1,
    }

    return render(request, "task/index.html", context=context)


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TaskSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = Task.objects.all().select_related("task_type")
        name = self.request.GET.get("name")
        if name:
            return queryset.filter(name__icontains=name)
        return queryset


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task:task-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("task:task-list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task:task-list")


@login_required
def toggle_assign_to_task(request, pk):
    worker = Worker.objects.get(id=request.user.id)
    if Task.objects.get(id=pk) in worker.tasks.all():
        worker.tasks.remove(pk)
    else:
        worker.tasks.add(pk)
    return HttpResponseRedirect(reverse_lazy("task:task-detail", args=[pk]))


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(WorkerListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = WorkerSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = Worker.objects.all()
        username = self.request.GET.get("username")
        if username:
            return queryset.filter(username__icontains=username)
        return queryset


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        worker_id = self.kwargs["pk"]

        worker = Worker.objects.get(id=worker_id)

        tasks_in_progress = worker.tasks.filter(is_completed=False)
        completed_tasks = worker.tasks.filter(is_completed=True)

        context["tasks_in_progress"] = tasks_in_progress
        context["completed_tasks"] = completed_tasks

        return context


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Worker
    form_class = WorkerCreationForm
    success_url = reverse_lazy("task:worker-list")


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerCreationForm
    success_url = reverse_lazy("task:worker-list")


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("")


@login_required
def finish_task(request, pk):
    task = Task.objects.get(id=pk)
    if datetime.now().date() <= task.deadline:
        task.status = "Completed on time"
    else:
        task.status = "Completed after the deadline"
    task.is_completed = True
    task.save()
    return HttpResponseRedirect(reverse_lazy("task:task-detail", args=[pk]))


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskTypeListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = TaskTypeSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        queryset = TaskType.objects.all()
        form = TaskTypeSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])

        return queryset


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("task:tasktype-list")


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("task:tasktype-list")


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    success_url = reverse_lazy("task:tasktype-list")


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PositionListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = TaskTypeSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        queryset = Position.objects.all()
        form = PositionSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])

        return queryset


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("task:position-list")


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("task:position-list")


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("task:position-list")

templates/task/index.html
{% extends "base.html" %}

{% block content %}
    <h1>IT Company Task Manager</h1>
    <p>Welcome to Best Task Manager Ever!</p>
    <h2>Information</h2>
    <p>The Task manager has the following record counts:</p>
    <ul>
        <li><strong>Workers:</strong> {{ num_workers }}</li>
        <li><strong>Tasks:</strong> {{ num_tasks }}</li>
        <li><strong>Positions:</strong> {{ num_positions }}</li>
    </ul>

    <p>You have visited this page
        {{ num_visits }} time{{ num_visits|pluralize }}.
    </p>

{% endblock %}

templates/task/position_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete position</h1>
  <p>Are you sure you want to delete the position "{{ position.name }}"?</p>

  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'task:position-list' %}" class="btn btn-secondary">No</a>
  </form>

{% endblock %}

templates/task/position_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} position</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task/position_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Positions List
    <a href="{% url 'task:position-create' %}" class="btn btn-primary link-to-page">
      Create new position
    </a>
  </h1>
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-secondary" type="submit" value="Search">
  </form>

  {% if position_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for position in position_list %}
        <tr>
          <td>{{ position.id }}</td>
          <td>{{ position.name }}</td>
          <td><a href="{% url 'task:position-update' pk=position.id %}">
              Update
            </a>
          </td>
          <td>
            <a style="color: red"
               href="{% url 'task:position-delete' pk=position.id %}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>There are no positions</p>
  {% endif %}
{% endblock %}

templates/task/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'task:task-detail' pk=task.id %}">
      <button type="button" class="btn btn-secondary">No</button>
     </a>
  </form>
{% endblock %}

templates/task/task_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Task: {{ task.name }}
    <a href="{% url 'task:task-delete' pk=task.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'task:task-update' pk=task.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>

    {% if user in task.assignees.all and not task.is_completed %}
      <a href="{% url 'task:finish-task' pk=task.id %}" class="btn btn-primary link-to-page">
        Finish task
      </a>
    {% endif %}
  </h1>

  <p><strong>Description:</strong> {{ task.description }}</p>
  <p><strong>Task type:</strong> {{ task.task_type }}</p>
  <p><strong>Priority:</strong> {{ task.priority }}</p>
  <p><strong>Status:</strong> {{ task.status }}</p>

  <p><strong>Deadline:</strong> {{ task.deadline }}</p>

  {{ task_in }}
  <div class="ml-3">
    <h4>Workers
      {% if task in user.tasks.all %}
        <a href="{% url 'task:toggle-task-assign' pk=task.id %}" class="btn btn-danger link-to-page">
          Delete me from this task
        </a>
      {% else %}
        <a href="{% url 'task:toggle-task-assign' pk=task.id %}" class="btn btn-success link-to-page">
          Assign me to this task
        </a>
      {% endif %}
    </h4>

    {% for worker in task.assignees.all %}
      <hr>
      <p><strong>Username:</strong>
        <a href="{% url "task:worker-detail" pk=worker.id %} ">{{ worker.username }}</a>
      </p>
      <p><strong>Position:</strong> {{ worker.position }}</p>
      {% if worker.email %}
        <p><strong>Email:</strong> {{ worker.email }}</p>
      {% endif %}
      {% if worker.first_name %}
        <p><strong>First name:</strong> {{ worker.first_name }}</p>
      {% endif %}
      {% if worker.last_name %}
        <p><strong>Last name:</strong> {{ worker.last_name }}</p>
      {% endif %}
    {% empty %}
      <p>No workers!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/task/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Task list
    <a href="{% url 'task:tasks-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
  <form method="get" action="" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-secondary" type="submit" value="Search">
  </form>
  {% if task_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Task type</th>
        <th>Deadline</th>
        <th>Status</th>
        <th>Priority</th>
      </tr>
      {% for task in task_list %}
        <tr>
          <td>{{ task.id }}</td>

          <td><a href="{% url "task:task-detail" pk=task.id %} ">{{ task.name }}</a>
          </td>
          <td>{{ task.task_type }}</td>
          <td>{{ task.deadline }}</td>
          <td>{{ task.status }}</td>
          <td>{{ task.priority }}</td>
        </tr>
      {% endfor %}

    </table>
  {% else %}
    <p>There are no tasks in the service.</p>
  {% endif %}
{% endblock %}

templates/task/tasktype_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Task Type</h1>
  <p>Are you sure you want to delete the task type "{{ task_type.name }}"?</p>

  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'task:tasktype-list' %}" class="btn btn-secondary">No</a>
  </form>

{% endblock %}

templates/task/tasktype_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task type</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task/tasktype_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Task Type List
    <a href="{% url 'task:tasktype-create' %}" class="btn btn-primary link-to-page">
      Create Task Type
    </a>
  </h1>
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-secondary" type="submit" value="Search">
  </form>

  {% if tasktype_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tasktype in tasktype_list %}
        <tr>
          <td>{{ tasktype.id }}</td>
          <td>{{ tasktype.name }}
          </td>
          <td>
            <a href="{% url 'task:tasktype-update' pk=tasktype.id %}">
              Update
            </a>
          </td>
          <td>
            <a style="color: red"
               href="{% url 'task:tasktype-delete' pk=tasktype.id %}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>There are no task type</p>
  {% endif %}
{% endblock %}

templates/task/worker_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete worker?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'task:worker-detail' pk=worker.id %}">
      <button type="button" class="btn btn-secondary">No</button>
     </a>
  </form>
{% endblock %}

templates/task/worker_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Worker: {{ worker.username }}
    <a href="{% url 'task:worker-delete' pk=worker.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>
    <a href="{% url 'task:worker-update' pk=worker.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
        {% if worker.email %}
        <p><strong>Email:</strong> {{ worker.email }}</p>
      {% endif %}
      {% if worker.first_name %}
        <p><strong>First name:</strong> {{ worker.first_name }}</p>
      {% endif %}
      {% if worker.last_name %}
        <p><strong>Last name:</strong> {{ worker.last_name }}</p>
      {% endif %}
  <p><strong>Position:</strong> {{ worker.position }}</p>

  <div class="ml-3">
    <h4>Tasks in progress</h4>
    {% if tasks_in_progress %}
      {% for task in tasks_in_progress %}
        <hr>
        <p><strong>Task name:</strong>
          <a href="{% url "task:task-detail" pk=task.id %} ">{{ task.name }}</a>
        </p>
        <p><strong>Task type:</strong> {{ task.task_type }}</p>
        <p><strong>Priority:</strong> {{ task.priority }}</p>
        <p><strong>Deadline:</strong> {{ task.deadline }}</p>
      {% endfor %}
    {% else %}
      <p>No tasks!</p>
    {% endif %}
    <h4>Completed tasks</h4>
    {% if completed_tasks %}
      {% for task in completed_tasks %}
        <hr>
        <p><strong>Task name:</strong>
          <a href="{% url "task:task-detail" pk=task.id %} ">{{ task.name }}</a>
        </p>
        <p><strong>Task type:</strong> {{ task.task_type }}</p>
        <p><strong>Priority:</strong> {{ task.priority }}</p>
        <p><strong>Deadline:</strong> {{ task.deadline }}</p>
      {% endfor %}
    {% else %}
      <p>No tasks!</p>
    {% endif %}
  </div>
{% endblock %}

templates/task/worker_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} worker</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}